# Generated by Django 5.1.2 on 2024-11-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_contact_alter_task_users_joinuser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinuser',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
