# Generated by Django 5.1.2 on 2024-11-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_alter_joinuser_icon_alter_joinuser_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(related_name='assignees', to='join_app.contact'),
        ),
    ]
