# Generated by Django 5.1.2 on 2024-11-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0006_alter_contact_firstname_alter_contact_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.BooleanField(default=False),
        ),
    ]
