# Generated by Django 5.1.2 on 2024-11-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0007_contact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='users',
            new_name='assignedTo',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='urgency',
        ),
    ]
