# Generated by Django 5.1.2 on 2024-11-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0008_rename_users_task_assignedto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='titel',
            new_name='content',
        ),
    ]
