# Generated by Django 5.1.2 on 2024-11-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0009_rename_titel_subtask_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignedTo',
            field=models.ManyToManyField(related_name='assignedTo', to='join_app.contact'),
        ),
    ]
