# Generated by Django 5.1.2 on 2024-11-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0011_alter_task_task_alter_task_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, related_name='assignedTo', to='join_app.contact'),
        ),
    ]
